using AsmResolver.DotNet;
using AssetRipper.Export.Configuration;
using AssetRipper.Export.Scripts;
using AssetRipper.Import.Configuration;
using AssetRipper.Import.Logging;
using AssetRipper.Import.Structure.Assembly;
using AssetRipper.Import.Structure.Assembly.Managers;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.ProjectDecompiler;

namespace AssetRipper.Export.UnityProjects.Scripts;

internal class ScriptDecompiler
{
	private readonly IAssemblyManager assemblyManager;
	private readonly ILSpyAssemblyResolver assemblyResolver;
	public LanguageVersion LanguageVersion { get; set; } = LanguageVersion.CSharp7_3;
	public ScriptContentLevel ScriptContentLevel { get; set; } = ScriptContentLevel.Level2;
	public ScriptingBackend ScriptingBackend { get; set; } = ScriptingBackend.Unknown;
	public bool FullyQualifiedTypeNames { get; set; } = false;
	public ScriptIlExportMode IlExportMode { get; set; } = ScriptIlExportMode.None;

	public ScriptDecompiler(IAssemblyManager assemblyManager)
	{
		this.assemblyManager = assemblyManager;
		assemblyResolver = new ILSpyAssemblyResolver(assemblyManager);
		ScriptingBackend = assemblyManager.ScriptingBackend;
	}

	public void DecompileWholeProject(AssemblyDefinition assembly, string outputFolder, FileSystem fileSystem)
	{
		CustomWholeProjectDecompiler decompiler = new(CreateSettings(), assemblyResolver, fileSystem);

		DecompileWholeProject(decompiler, assembly, outputFolder);

		//Only recovered bodies produce source that does not compile, and only Level3 recovers any.
		if (ScriptContentLevel == ScriptContentLevel.Level3)
		{
			InvalidSourceRepair.Apply(assembly, assemblyManager, GetRoslynLanguageVersion(), outputFolder, fileSystem);
		}

		//Written last, so that a companion describes the source that was actually kept.
		if (IlExportMode == ScriptIlExportMode.Companion)
		{
			ScriptIlCompanionExporter.Export(assembly, decompiler.Settings.UseNestedDirectoriesForNamespaces, outputFolder, fileSystem);
		}
	}

	/// <summary>
	/// The version the decompiled source is written for, in the compiler's own terms.
	/// </summary>
	/// <remarks>
	/// The two enums name the same versions, but the decompiler spells the whole numbered ones with a trailing zero:
	/// its CSharp9_0 is the compiler's CSharp9. A version too new for the compiler to know falls back to its latest.
	/// </remarks>
	private Microsoft.CodeAnalysis.CSharp.LanguageVersion GetRoslynLanguageVersion()
	{
		string name = LanguageVersion.ToString();
		if (name.EndsWith("_0", StringComparison.Ordinal))
		{
			name = name[..^2];
		}

		return Enum.TryParse(name, out Microsoft.CodeAnalysis.CSharp.LanguageVersion version)
			? version
			: Microsoft.CodeAnalysis.CSharp.LanguageVersion.Latest;
	}

	private DecompilerSettings CreateSettings()
	{
		DecompilerSettings settings = new();

		settings.SetLanguageVersion(LanguageVersion);

		settings.AlwaysShowEnumMemberValues = true;
		settings.ShowXmlDocumentation = true;

		settings.UseNestedDirectoriesForNamespaces = true;

		if (FullyQualifiedTypeNames)
		{
			settings.AlwaysUseGlobal = true;
			settings.UsingDeclarations = false;
		}

		return settings;
	}

	private void DecompileWholeProject(WholeProjectDecompiler decompiler, AssemblyDefinition assembly, string outputFolder)
	{
		try
		{
			decompiler.DecompileProject(assemblyResolver.Resolve(assembly), outputFolder, TextWriter.Null);
		}
		catch (Exception exception)
		{
			Logger.Error(exception);
		}
	}

	private sealed class CustomWholeProjectDecompiler(DecompilerSettings settings, ILSpyAssemblyResolver assemblyResolver, FileSystem fileSystem) : ILSpyWholeProjectDecompiler(settings, assemblyResolver, NullProjectFileWriter.Instance, fileSystem)
	{
		protected override TextWriter CreateFile(string path)
		{
			if (FileSystem.Path.GetFileName(path) is "UnitySourceGeneratedAssemblyMonoScriptTypes_v1.cs")
			{
				// UnitySourceGeneratedAssemblyMonoScriptTypes_v1 is generated by Unity and should not be decompiled
				return TextWriter.Null;
			}

			return base.CreateFile(path);
		}
	}
}
